project:
  type: book
  output-dir: _book

book:
  title: "City Scan Technical Reference"
  author: "World Bank - City Resilience Program"
  date: "5/5/2026"
  search: true
  repo-url: https://github.com/cityresilience/city-scan/
  page-footer:
    background: dark
    left: |
      ![](image/GFDRR_Primary Logo_White.svg){width=250px}
    right: |
      City Scan is a product of GFDRR - World Bank's [City Resilience Program](https://www.gfdrr.org/en/crp).
  cover-image: image/cover.png
  
  # favicon: cover.jpg
  sidebar:
    logo: image/CRP_LOGO.jpeg
    style: "docked"
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "City Scan Overview"
      chapters: 
        - what-is-cityscan.qmd
        - examples-cityscan.qmd
    - part: "Standard Workflow"
      chapters: 
        - at-a-glance.qmd 
        - setting-up.qmd
        - inputs-config.qmd
        - running-first-cityscan.qmd
    - part: "Advanced Workflow"
      chapters: 
        - multiple-cityscan.qmd
        - custom-cityscan.qmd 
        - adding-dataset.qmd
    - part: "Tasks & Data Layers"
      chapters: 
        - tasks-structure-overview.qmd
        - population-demographic.qmd
        - economic-activity.qmd
        - built-form.qmd
        - climate-condition.qmd
        - risk-identification.qmd
    - part: "Understanding the Repo"
      chapters: 
        - repo-structure.qmd
        - task-dependency.qmd
    - part: "Case Studies & Galleries"
      chapters: 
        - case-standard-rabat.qmd
        - case-multiple-philippines.qmd
    - part: "Collaborating"
      chapters:
        - git-guide.qmd
        - reporting-issues.qmd
        - contributing.qmd
        - sharing-the-guide.qmd
        - editing-this-reference.qmd
    - references.qmd

bibliography: references.bib
reference-location: document
citation-location: document

format:
  html:
    theme:
      - cosmo
      - brand
    code-fold: true
    number-depth: 3
  pdf:
    documentclass: scrreprt
    number-depth: 3

execute:
  freeze: true



